version: '3'

services:
  service:
    image: "node:9.5.0-alpine"
    ports: 
      - "4000:4000"
    volumes:
      - ".:/usr/src/app"
    working_dir: "/usr/src/app"
    depends_on: 
      - "database"
    command: /bin/sh -c "yarn && yarn develop"

  database:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo:/data/db"
